FROM base_image

ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

ADD aqfer/scripts /scripts
ADD aqfer/aws/ec_template_app_spec.yml /ec_template_app_spec.yml
ADD aqfer/aws/ecs_template_app_spec.yml /ecs_template_app_spec.yml

WORKDIR /
