FROM ubuntu

# Throw away till here
ADD ./caddy/caddy /caddy
ADD ./aqfer/Caddyfile /Caddyfile
ADD ./aqfer/.secrets.yml /.secrets.yml
ADD ./aqfer/test.go /test.go
ADD ./aqfer/scripts/run_unit_tests.sh /run_unit_tests.sh
ADD ./aqfer/integration_tests/ /aqfer/integration_tests/
ADD ./aqfer/scripts/run_integration_tests.sh /run_integration_tests.sh
ADD ./aqfer/scripts/run_sanity_tests.sh /run_sanity_tests.sh
RUN mkdir /temp_cache

WORKDIR /
CMD ./caddy
