AWSTemplateFormatVersion: '2010-09-09'
Description: DB deployment
Parameters:
  AWSAccount:
    Description: Aws Account Id
    Type: String
  AvailabilityZone:
    Description: Availability Zone
    Type: String
  DaxName:
    Description: DAX cluster name
    Type: String
  DaxNodeType:
    Default: dax.r3.large
    Description: DAX cluster size
    Type: String
  DaxRoleName:
    Description: IAM Role for DAX cluster
    Type: String
  DaxSecurityGroupName:
    Description: Security Group name for DAX cluster
    Type: String
  DaxSubnetGroupName:
    Description: DAX Subnet Group name
    Type: String
  DynamoTableName:
    Description: Name for Dynamo table
    Type: String
  ECClusterName:
    Description: Elasticache Cluster name
    Type: String
  ECNodeType:
    Default: cache.t2.micro
    Description: Elasticache cache size
    Type: String
  ECSecurityGroupName:
    Description: Security Group name for Elasticache
    Type: String
  ECSubnetGroupName:
    Description: Subnet Group name for Elasticache
    Type: String
  PartitionKey:
    Description: Partition Key for Dynamo Table
    Type: String
  SortKey:
    Description: Sort Key for Dynamo Table
    Type: String
  Subnet:
    Description: VPC Zone Identifier
    Type: String
  Vpc:
    Description: VPC Identifier
    Type: String
Resources:
  DaxCluster:
    DependsOn: DaxSubnetGroup
    Properties:
      AvailabilityZones:
      - Ref: AvailabilityZone
      ClusterName:
        Ref: DaxName
      IAMRoleARN:
        Fn::GetAtt:
        - DaxRole
        - Arn
      NodeType:
        Ref: DaxNodeType
      ReplicationFactor: 1
      SecurityGroupIds:
      - Ref: DaxSecurityGroup
      SubnetGroupName:
        Ref: DaxSubnetGroupName
    Type: AWS::DAX::Cluster
  DaxRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: dax.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - s3:Get*
            - s3:List*
            Effect: Allow
            Resource: '*'
          - Action:
            - dynamodb:BatchGetItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:BatchWriteItem
            - dynamodb:DeleteItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DescribeLimits
            - dynamodb:DescribeTimeToLive
            - dynamodb:DescribeTable
            - dynamodb:ListTables
            Effect: Allow
            Resource:
            - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWSAccount}:table/${DynamoTableName}
        PolicyName: DaxPolicy
      RoleName:
        Ref: DaxRoleName
    Type: AWS::IAM::Role
  DaxSecurityGroup:
    Properties:
      GroupDescription: Dax Security Group
      GroupName:
        Ref: DaxSecurityGroupName
      VpcId:
        Ref: Vpc
    Type: AWS::EC2::SecurityGroup
  DaxSubnetGroup:
    Properties:
      Description: DAX Subnet Group
      SubnetGroupName:
        Ref: DaxSubnetGroupName
      SubnetIds:
      - Ref: Subnet
    Type: AWS::DAX::SubnetGroup
  DynamoDBTable:
    Properties:
      AttributeDefinitions:
      - AttributeName:
          Ref: PartitionKey
        AttributeType: S
      - AttributeName:
          Ref: SortKey
        AttributeType: S
      KeySchema:
      - AttributeName:
          Ref: PartitionKey
        KeyType: HASH
      - AttributeName:
          Ref: SortKey
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '500'
        WriteCapacityUnits: '5'
      TableName:
        Ref: DynamoTableName
    Type: AWS::DynamoDB::Table
  ECSecurityGroup:
    Properties:
      GroupDescription: Elasticache Security Group
      GroupName:
        Ref: ECSecurityGroupName
      VpcId:
        Ref: Vpc
    Type: AWS::EC2::SecurityGroup
  ECSubnetGroup:
    Properties:
      CacheSubnetGroupName:
        Ref: ECSubnetGroupName
      Description: Elasticache Subnet Group
      SubnetIds:
      - Ref: Subnet
    Type: AWS::ElastiCache::SubnetGroup
  ElastiCache:
    Properties:
      CacheNodeType:
        Ref: ECNodeType
      CacheSubnetGroupName:
        Ref: ECSubnetGroup
      ClusterName:
        Ref: ECClusterName
      Engine: redis
      NumCacheNodes: 1
      PreferredAvailabilityZone:
        Ref: AvailabilityZone
      VpcSecurityGroupIds:
      - Ref: ECSecurityGroup
    Type: AWS::ElastiCache::CacheCluster
