---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS deployment'
Parameters:
  Id:
    Description: 'AWS access key id'
    Type: String
  Secret:
    Description: 'AWS access secret key'
    Type: String
  Jwt:
    Description: 'JWT secret'
    Type: String
  Version:
    Description: 'Application version'
    Type: String
  RootName:
    Description: 'Application Name root'
    Type: String
  AWSAccount:
    Description: 'Aws Account Id'
    Type: String
  Ami:
    Description: 'Ami template for linux EC2 instance'
    Default: 'ami-55ef662f'
    Type: String
  AppName:
    Description: 'Root name and version combination, for use in other components'
    Type: String
  InstanceType:
    Description: 'EC2 Instance Type'
    Default: 't2.micro'
    Type: String
  KeyPair:
    Description: 'EC2 Key Pair'
    Type: String
  SecurityGroupName:
    Description: 'Security Group name for EC2 instances'
    Type: String
  EC2InstanceRoleName:
    Description: 'IAM Role name for EC2 instances'
    Type: String
  ClusterName:
    Description: 'ECS Cluster name'
    Type: String
  TaskDefinitionName:
    Description: 'ECS Task Definition name'
    Type: String
  ECRRepoURI:
    Description: 'Repo URI for uplated ECR container'
    Type: String
  DynamoTableName:
    Description: 'Name for Dynamo table'
    Type: String

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: partition-key
        AttributeType: S
      - AttributeName: sort-key
        AttributeType: S
      KeySchema:
      - AttributeName: partition-key
        KeyType: HASH
      - AttributeName: sort-key
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName: DynamoTableName

  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref EC2InstanceRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: ECSPolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - s3:Get*
            - s3:List*
            Resource: "*"
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource:
            - !Sub 'arn:aws:logs:us-east-1:${AWSAccount}:log-group:*'
          - Effect: Allow
            Action:
            - cloudformation:*
            - codedeploy:*
            - ec2:*
            - ecs:*
            - ecr:*
            - iam:AddRoleToInstanceProfile
            - iam:CreateInstanceProfile
            - iam:CreateRole
            - iam:DeleteInstanceProfile
            - iam:DeleteRole
            - iam:DeleteRolePolicy
            - iam:GetRole
            - iam:PassRole
            - iam:PutRolePolicy
            - iam:RemoveRoleFromInstanceProfile
            Resource: "*"
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
      - Ref: EC2InstanceRole
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          default:
          - runtask
        runtask:
          commands:
            c:
              command: service awslogs restart
            d:
              command: sudo service docker restart
            e:
              command: sudo start ecs
            f:
              command: !Sub 'aws ecs run-task --cluster ${ClusterName} --task-definition ${TaskDefinitionName} --region ${AWS::Region}'
    Properties:
      AssociatePublicIpAddress: true
      BlockDeviceMappings:
      - DeviceName: "/dev/xvdcz"
        Ebs:
          VolumeSize: 22
          VolumeType: gp2
      EbsOptimized: false
      IamInstanceProfile:
        Ref: EC2InstanceProfile
      ImageId: !Ref Ami
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPair
      SecurityGroups:
      - Ref: SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          # Setup for EC2 instance to register to ECS cluster
          sudo yum install -y ecs-init
          echo ECS_CLUSTER=${ClusterName} >> /etc/ecs/ecs.config
          echo ECS_LOGLEVEL=debug >> /etc/ecs/ecs.config
          echo ECS_AVAILABLE_LOGGING_DRIVERS=''["awslogs"]'' >> /etc/ecs/ecs.config

          # Cloudformation setup to signal and error -- cfn-bootstrap not needed with current ami
          # wget https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.amzn1.noarch.rpm
          yum -y install aws-cfn-bootstrap-latest.amzn1.noarch.rpm
          function error_exit {
            /opt/aws/bin/cfn-signal -e 1 --reason "$1" --stack ${AWS::StackName} --resource LaunchConfiguration --region ${AWS::Region}
            exit 1
          }

          # Setup for ecs-agent cloudwatch logs configuration
          echo [/var/log/ecs/ecs-agent.log] >> /ecs_logs.conf
          echo file = /var/log/ecs/ecs-agent.log.* >> /ecs_logs.conf
          echo log_group_name = /var/log/ecs/ecs-agent.log >> /ecs_logs.conf
          echo log_stream_name = ${ClusterName}/INSTANCE_ID >> /ecs_logs.conf
          /opt/aws/bin/ec2-metadata -i | sed 's/instance-id: //' >> /instance_id
          cat /ecs_logs.conf | sed ''s/INSTANCE_ID/''$(cat /instance_id)''/'' > /ecs_logs.conf
          mkdir -p /var/awslogs/etc/config
          ln -s /ecs_logs.conf /var/awslogs/etc/config/ecs_logs.conf

          # Setup awslogs agent, signal ecs setup complete
          wget https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py || error_exit 'Failed to download AWS Logs Agent.'
          chmod +x ./awslogs-agent-setup.py
          python awslogs-agent-setup.py -n -r ${AWS::Region} -c s3://aws-codedeploy-us-east-1/cloudwatch/awslogs.conf || error_exit 'Failed run awslogs-agent-setup.py.'
          /opt/aws/bin/cfn-signal -e 0 --reason "AWS ECS Agent setup complete." --stack ${AWS::StackName} --resource LaunchConfiguration --region ${AWS::Region}

          # Start Cloudformation Init
          /opt/aws/bin/cfn-init --stack ${AWS::StackName} --resource LaunchConfiguration --region ${AWS::Region}

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      TargetGroupARNs: []
      DesiredCapacity: 1
      Tags: []
      LoadBalancerNames: []
      Cooldown: 300
      MinSize: 0
      MaxSize: 1
      VPCZoneIdentifier:
      - subnet-7a8a5255
      HealthCheckGracePeriod: 0
      HealthCheckType: EC2
      TerminationPolicies:
      - Default
      LaunchConfigurationName: !Ref LaunchConfiguration

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${ClusterName}'
  ECSTaskDefitinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Volumes: []
      Family: !Ref TaskDefinitionName
      PlacementConstraints: []
      ContainerDefinitions:
      - DnsSearchDomains: []
        Environment:
        - Name: "AWS_ACCESS_KEY_ID"
          Value: !Ref Id
        - Name: "AWS_SECRET_ACCESS_KEY"
          Value: !Ref Secret
        - Name: "AWS_REGION"
          Value: !Sub "${AWS::Region}"
        - Name: "JWT_SECRET"
          Value: !Ref Jwt
        ReadonlyRootFilesystem: false
        Name: caddy
        Links: []
        MountPoints: []
        Image: !Ref ECRRepoURI
        LinuxParameters:
          Capabilities: {}
        Essential: true
        PortMappings:
        - Protocol: tcp
          ContainerPort: 8082
          HostPort: 8082
        DnsServers: []
        DockerSecurityOptions: []
        EntryPoint: []
        Ulimits: []
        Privileged: false
        Memory: 300
        Command: []
        ExtraHosts: []
        Cpu: 0
        VolumesFrom: []
        DockerLabels: {}
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref SecurityGroupName
      GroupDescription: 'Security Group for EC2 instances'
      VpcId: vpc-f582e28d
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '8082'
        ToPort: '8082'
        CidrIp: 0.0.0.0/0
