name: Issue
description: An actionable development item, like a bug report or feature request
body:
  - type: textarea
    id: content
    attributes:
      placeholder: Write the bug report or feature request here. Be specific by providing complete logs, or a detailed proposal, etc.
    validations:
      required: true
  - type: dropdown
    id: ai-disclosure
    attributes:
      label: AI Disclosure
      description: Our project allows contributors to use AI/LLM tooling, but requires that it be disclosed, including for language/translation purposes. Please certify whether you have used any such tooling related to this issue:
      options:
        - AI used
        - AI not used
    validations:
      required: true
  - type: input
    id: ai-description
    attributes:
      label: If AI was used, to what extent was it used?