FROM aqfer-caddy:latest

# RUN apt-get update
# RUN apt-get -y install vim

ADD ./Caddyfile /Caddyfile
ADD ./test.yml /.secrets.yml

# auth test
RUN mkdir -p /v1
RUN cp /test.go /v1/test.go

# transformrequest test
RUN mkdir -p /v1/cids/asdf/entity_types/asdf/domains/asdf/keys/asdf/
RUN cp /test.go /v1/cids/asdf/entity_types/asdf/domains/asdf/keys/asdf/test.go

WORKDIR /
CMD ./caddy
