FROM aqfer-caddy:latest

# RUN apt-get update
# RUN apt-get -y install vim

ADD ./Caddyfile /Caddyfile

# auth test
RUN mkdir -p /v1
RUN cp /main.go /v1/main.go

# transformrequest test
RUN mkdir -p /v1/cids/c009/entity_types/asdf/domains/asdf/keys/asdf/
RUN cp /main.go /v1/cids/c009/entity_types/asdf/domains/asdf/keys/asdf/main.go

WORKDIR /
CMD ./caddy
