name: CGO Build

on:
  push:
    branches:
      - master
      - 2.*
  pull_request:
    branches:
      - master
      - 2.*

jobs:
  cgo-build-test:
    strategy:
      fail-fast: false
      matrix:
        goos: ['linux']
        go: [ '1.16', '1.17' ]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Print Go version and environment
        id: vars
        run: |
          printf "Using go at: $(which go)\n"
          printf "Go version: $(go version)\n"
          printf "\n\nGo environment:\n\n"
          go env
          printf "\n\nSystem environment:\n\n"
          env
          echo "::set-output name=go_cache::$(go env GOCACHE)"

      - name: Cache the build cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.vars.outputs.go_cache }}
          key: cgo-build-go${{ matrix.go }}-${{ matrix.goos }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            cgo-build-go${{ matrix.go }}-${{ matrix.goos }}

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2

      # Run the build with CGO enabled, to verify that the build still
      # passes, even without installing anything extra. This test should
      # fail if we add any dependencies that optionally uses CGO.
      - name: Run Build
        env:
          CGO_ENABLED: 1
          GOOS: ${{ matrix.goos }}
        shell: bash
        continue-on-error: true
        working-directory: ./cmd/caddy
        run: |
          GOOS=$GOOS go build -trimpath -o caddy-"$GOOS"-amd64
          if [ $? -ne 0 ]; then
            echo "::warning ::$GOOS CGO Build Failed"
            exit 0
          fi
